[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7"
tokio = { version = "1.37", features = ["full"] }
tower = { version = "0.4", features = ["util"] }
dotenvy = "0.15"
rusqlite = { version = "0.31", features = ["bundled"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hyper = { version = "1.2", features = ["full"] }
tower-http = { version = "0.5", features = ["cors", "fs"] }
tracing = "0.1.41"
mailin-embedded = { features = ["rtls"], version = "0.8.3"}
mail-parser = "0.11"
futures-util = "0.3"
async-stream = "0.3"

[dev-dependencies]
tempfile = "3.10"
tokio-test = "0.4"
